#ifndef INFORMATION_H
#define INFORMATION_H

#define WINDOW_ADDSTAT_STR 1
#define WINDOW_ADDSTAT_STA 2
#define WINDOW_ADDSTAT_AGI 3
#define WINDOW_ADDSTAT_INT 4
#define WINDOW_ADDSTAT_PVP 5

#endif